name: Enviar agenda a Discord

on:
  schedule:
    - cron: "0 8 * * 5" # Viernes 10:00 hora España (8:00 UTC)
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Debug secret
  run: |
    if [ -z "$DISCORD_WEBHOOK" ]; then
      echo "❌ El secreto está vacío"
      exit 1
    else
      echo "✅ El secreto existe (longitud: ${#DISCORD_WEBHOOK})"
    fi
  env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Run script
        run: node agenda.js
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
